name: Test and Deploy
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        otp: [23.1]
        elixir: [1.11.1]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with: 
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.0

    - name: Cache Elixir deps
      uses: actions/cache@v1
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Cache Elixir _build
      uses: actions/cache@v1
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }} 

    - name: Cache Node modules
      uses: actions/cache@v1
      id: node-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('assets/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install deps
      run: |
        mix deps.get
        npm install --prefix assets
    - run: mix test

  deploy:
    needs: test # Will only run if the test job succeeds
    if: github.ref == 'refs/heads/main' # Only run this job if it is on the main branch

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main # Check out main instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch
          
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1
          
      - uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_APP: cointrader # Feel free to also put this in your secrets
          GIGALIXIR_CLEAN: true # defaults to false
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          MIGRATIONS: false  # defaults to true
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}